language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc g++ make libsdl1.2-dev; fi

script:
  - cargo build --verbose --all
  - cargo test --verbose --all