language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - sudo apt-get install gcc g++ make libsdl1.2-dev
  - cargo build --verbose --all
  - cargo test --verbose --all